### PR TITLE
added check for __main__ 

### PR DESCRIPTION
**Pull request by nevemlaci**

### CODE REVIEW

**Comment by Gilgames32** [comment]
this completely ignores what i just said, use a main function

**Review by Gilgames32 — CHANGES_REQUESTED** [review]
refer to my previous comments

**Comment by nevemlaci** [comment]
Okay I literally pred the wrong code so what you wont merge it anyways cuz u like bad code :3

**Comment by nevemlaci** [comment]
nah there u go

**Comment by nevemlaci** [comment]
> refer to my previous comments

Did it lil bro :3

**Comment by Gilgames32** [comment]
._.

**Pull request merged**
